version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/taxassistant
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: taxassistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
